#!/bin/bash
# Local (test only): build | package | smoke
# CI only: publish <version> | all <version>

set -euo pipefail

GOPENPGP_REPO="https://github.com/mssun/gopenpgp.git"
GOPENPGP_TAG="v2.10.0-passforios"
GOPENPGP_SHA="a70794d838402668f2604c994d45086e329311e9"
GOMOBILE_VERSION="v0.0.0-20260908204917-8b95e45f8d3e"
GO_VERSION="1.26.0"
IOS_VERSION="13.0"
MACOS_VERSION="10.15"
FRAMEWORK="Gopenpgp"

ROOT="$(pwd)"
export GOPATH="$ROOT/go"
export PATH="$PATH:$GOPATH/bin"

OUTPUT_PATH="$ROOT/go/dist"
GOPENPGP_PATH="$ROOT/go/checkout/gopenpgp"
XCFRAMEWORK="$OUTPUT_PATH/$FRAMEWORK.xcframework"
ZIP="$OUTPUT_PATH/$FRAMEWORK.xcframework.zip"

fail() {
  echo "error: $*" >&2
  exit 1
}

build() {
  rm -rf "$GOPENPGP_PATH" "$XCFRAMEWORK"
  mkdir -p "$OUTPUT_PATH" "$(dirname "$GOPENPGP_PATH")"

  git clone --depth 1 --branch "$GOPENPGP_TAG" "$GOPENPGP_REPO" "$GOPENPGP_PATH"
  [ "$(git -C "$GOPENPGP_PATH" rev-parse HEAD)" = "$GOPENPGP_SHA" ] \
    || fail "$GOPENPGP_TAG does not match pinned SHA $GOPENPGP_SHA"

  pushd "$GOPENPGP_PATH" >/dev/null
  go get "golang.org/x/mobile/cmd/gomobile@$GOMOBILE_VERSION"
  go get "golang.org/x/mobile/cmd/gobind@$GOMOBILE_VERSION"
  go build golang.org/x/mobile/cmd/gomobile
  go build golang.org/x/mobile/cmd/gobind
  go mod download github.com/ProtonMail/go-crypto
  ./gomobile init
  ./gomobile bind -tags mobile -target ios,iossimulator,macos \
    -iosversion "$IOS_VERSION" -macosversion "$MACOS_VERSION" -v -ldflags="-s -w" \
    -o "$XCFRAMEWORK" \
    github.com/ProtonMail/gopenpgp/v2/crypto \
    github.com/ProtonMail/gopenpgp/v2/armor \
    github.com/ProtonMail/gopenpgp/v2/constants \
    github.com/ProtonMail/gopenpgp/v2/models \
    github.com/ProtonMail/gopenpgp/v2/subtle \
    github.com/ProtonMail/gopenpgp/v2/helper
  popd >/dev/null
}

package() {
  [ -d "$XCFRAMEWORK" ] || fail "run build first"
  rm -f "$ZIP"
  ditto -c -k --keepParent "$XCFRAMEWORK" "$ZIP"
  swift package compute-checksum "$ZIP" | tee "$ZIP.checksum"
}

smoke() {
  [ -f "$ZIP" ] || fail "run package first"
  local dir
  dir="$(mktemp -d)"
  mkdir -p "$dir/Sources/Smoke"
  cp "$ZIP" "$dir/"
  cat > "$dir/Package.swift" <<EOF
// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "Smoke",
    platforms: [.iOS(.v13), .macOS(.v10_15)],
    targets: [
        .binaryTarget(name: "$FRAMEWORK", path: "$FRAMEWORK.xcframework.zip"),
        .target(name: "Smoke", dependencies: ["$FRAMEWORK"]),
    ]
)
EOF
  echo "import $FRAMEWORK" > "$dir/Sources/Smoke/Smoke.swift"
  (cd "$dir" && swift build)
  rm -rf "$dir"
}

generate_manifest() {
  local url="$1" checksum="$2"
  cat > Package.swift <<EOF
// swift-tools-version:5.9
// Generated by gopenpgp_build.sh - do not edit.
import PackageDescription

let package = Package(
    name: "spm-gopengpg",
    platforms: [.iOS(.v13), .macOS(.v10_15)],
    products: [
        .library(name: "$FRAMEWORK", targets: ["$FRAMEWORK"]),
    ],
    targets: [
        .binaryTarget(
            name: "$FRAMEWORK",
            url: "$url",
            checksum: "$checksum"
        ),
    ]
)
EOF
}

publish() {
  [ "${GITHUB_ACTIONS:-}" = "true" ] || fail "publish runs in CI only (release workflow)"
  local version="${1:-}"
  [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "version must look like 2.10.0"
  [ -f "$ZIP" ] || fail "run package first"

  local repo checksum url verify_dir
  repo="${GITHUB_REPOSITORY:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"
  checksum="$(swift package compute-checksum "$ZIP")"
  url="https://github.com/$repo/releases/download/$version/$FRAMEWORK.xcframework.zip"

  git ls-remote --exit-code --tags origin "refs/tags/$version" >/dev/null 2>&1 \
    && fail "tag $version already exists"
  git rev-parse -q --verify "refs/tags/$version" >/dev/null && fail "tag $version already exists locally"

  gh release create "$version" "$ZIP" --draft --title "$version" \
    --notes "gopenpgp fork tag $GOPENPGP_TAG (commit $GOPENPGP_SHA), gomobile $GOMOBILE_VERSION, Go $GO_VERSION"

  verify_dir="$(mktemp -d)"
  gh release download "$version" --pattern "$FRAMEWORK.xcframework.zip" --dir "$verify_dir"
  [ "$(swift package compute-checksum "$verify_dir/$FRAMEWORK.xcframework.zip")" = "$checksum" ] \
    || fail "uploaded asset checksum mismatch; delete draft $version and retry"
  rm -rf "$verify_dir"

  git pull --rebase origin main
  generate_manifest "$url" "$checksum"
  git add Package.swift
  git commit -m "chore: release $version"
  git tag "$version"
  git push origin HEAD "refs/tags/$version"
  gh release edit "$version" --draft=false
}

case "${1:-}" in
  build) build ;;
  package) package ;;
  smoke) smoke ;;
  publish) publish "${2:-}" ;;
  all) [ "${GITHUB_ACTIONS:-}" = "true" ] || fail "all runs in CI only (release workflow)"; build; package; smoke; publish "${2:-}" ;;
  *) fail "usage: $0 build | package | smoke | publish <version> | all <version>" ;;
esac
