// swift-tools-version:5.9
// Generated by gopenpgp_build.sh - do not edit.
import PackageDescription

let package = Package(
    name: "spm-gopengpg",
    platforms: [.iOS(.v13), .macOS(.v10_15)],
    products: [
        .library(name: "Gopenpgp", targets: ["Gopenpgp"]),
    ],
    targets: [
        .binaryTarget(
            name: "Gopenpgp",
            url: "https://github.com/amine2233/spm-gopengpg/releases/download/2.10.0/Gopenpgp.xcframework.zip",
            checksum: "e4e10ac81fc1684006728a5c9bc552e917efbb819783aa2963fe471f72328a5f"
        ),
    ]
)
